### ISSUE TITLE
Build instructions for both physical device and firmware

### ISSUE THREAD

**Issue by nikitalita** [necroware/gameport-adapter#14]
Are there instructions available on how to build this device?

And also how to build the firmware?

**Comment by necroware** [comment]
You mean, how to solder it? There is not much to say, four resistors, joystick port and an Arduino. And if you want to know how to build an Arduino projects, I'd suggest to start with something simple, like blinking LEDs. The Arduino IDE has a lot of nice examples for the beginners.

**Comment by creopard** [comment]
The firmware has to be opened directly in the Arduino IDE. It will then be able to compile it for you and can transfer the compiled result directly to the connected Arduino board via USB.

**Comment by nikitalita** [comment]
Where did you get the custom PCB for the dip-24-to-DB15? Can we buy that somewhere?

**Comment by amak79** [comment]
@nikitalita

You can use a PCB manufacturing service like JLCPCB or PCBWay. All you need to do is upload the `gameport-adapter-gerber-v0.2.zip` file from the releases page and you will be given a quote.

**Comment by msgit0** [comment]
I was hoping for something like a schematic diagram to understand what pins on the DB15 connect to which pins on the Arduino, and how the resistors fit into the circuit.  I've been trying to create a similar device for AGES using a Teensy 2.0 board (similar to Arduino).  My joystick is the Logitech Wingman Digital Extreme, using what I hear is the Logitech ADI protocol (something else I can find no information on).  I have only been successful at reading the state for the basic 4 buttons.

**Comment by necroware** [comment]
This is an open source project. Here you can find all the circuits, the PCB, the software and the ADI protocol implementation among other digital protocols. Everything is open, so I really don't get the point of your question.

**Comment by msgit0** [comment]
Thank you for the prompt reply.  I have downloaded the code, and it appears I need to install KICAD in order to view the schematic.  I'll do that now.

**Comment by rdfry** [comment]
Nikitalita the board is self explanatory.

**Comment by nikitalita** [comment]
I built it myself, I understand it now :)
