### ISSUE TITLE
Support for analog devices with more than 4 buttons

### ISSUE THREAD

**Issue by ai0010** [necroware/gameport-adapter#22]
Hello

It's been a while that I've spent time messing with firmware, but I still failed on figure out how to support analog devices with more than 4 bottons.
For example:
B4 = B0 + B1
B5 = B0 + B2
B6 = B1 + B2
Could you provide an example or tutorial on that?
Thanks.

Nissin

**Comment by necroware** [comment]
Hi, unfortunately I don't understand your question. Some joysticks allow to use combinations of buttons to emulate more buttons, just as you wrote, but what exactly do you want to know?

**Comment by ai0010** [comment]
It was because I am new to Arduino and cannot understand the syntax. No longer an issue now.
