### ISSUE TITLE
Machined-pin socket in bill of materials

### ISSUE THREAD

**Issue by keronian** [necroware/gameport-adapter#28]
The socket that was called out in the Bill of Materials is for machined pin (round) headers.  This causes problems if trying to insert an arduino using the standard square pins that it comes with.

Should either switch the BOM to something like 3M5467-ND or 3M5479-ND or at the very least call out the need to get machined-pin breakaway headers like maybe 1988-1163-ND?

**Comment by necroware** [comment]
Already resolved with with this pull request:
https://github.com/necroware/gameport-adapter/pull/27
