### ISSUE TITLE
Logitech Wingman Interceptor, Pov(Hat) displayed as single and not working in windows panel

### ISSUE THREAD

**Issue by Fanbotica** [necroware/gameport-adapter#67]
Fixed the timing problems that prevented the glorious Logitech Wingman Interceptor from being detected, here a new problem appears, in the control panel of the game peripheral properties in Windows, a single POV/Hat is displayed, the Logitech Wingman Interceptor joystick has it well 3, and furthermore this is not activated in the test area.

![Logitech Wingman Interceptor_1_pov](https://github.com/necroware/gameport-adapter/assets/19761970/eb8f4f42-782e-4d2d-ab40-ac18f1ba1c49)

**Comment by necroware** [comment]
Hi the amount of hats, axes and buttons is reported by the joystick and is decoded in `Logitech::readMetaData()` function. Please take a look at that and try to find out if something is wrong there. ADI protocol (which is used by Logitech) supports one primary hat and multiple secondary hats. I assume, that the number of secondary hats is not decoded properly.

**Comment by Fanbotica** [comment]
> Hi the amount of hats, axes and buttons is reported by the joystick and is decoded in `Logitech::readMetaData()` function. Please take a look at that and try to find out if something is wrong there. ADI protocol (which is used by Logitech) supports one primary hat and multiple secondary hats. I assume, that the number of secondary hats is not decoded properly.

Ok necroware, I was just starting to explore the functions regarding the metadata, their decoding. Furthermore I will try to understand if the offsets of the bits taken from the getBits() function and the number of bits considered for the hats are correct for the Wingman Interceptor.
I plan to update you as soon as possible..

**Comment by Fanbotica** [comment]
So, I activated the "NDEBUG" log function (activated by commenting it) in the Utilities.h file and added some lines to print the values obtained from the getBits() function in the readMetaData() function on the screen.

If needed, the added lines are these:

     log("Meta data package size: %d", metaSize);
     log("Device ID: %d", m_metaData.deviceID);
     log("Flags: %d", flags);
     log("Number of Hats: %d", m_metaData.numHats);
     log("Number of Hat Directions: %d", m_metaData.numHatDirections);
     log("Number of Secondary Buttons: %d", m_metaData.numSecondaryButtons);
     log("Number of Axes (8-bit): %d", num8bitAxes);
     log("Number of Axes (10-bit): %d", m_metaData.num10bitAxes);
     log("Device Name: %s", m_metaData.deviceName);

The output on the serial monitor is as follows:

17:17:48.934 -> Meta data package size: 106
17:17:48.934 -> Device ID: 4
17:17:48.934 -> Flags: 12
17:17:48.934 -> Number of Hats: 3
17:17:48.934 -> Number of Hat Directions: 8
17:17:48.934 -> Number of Secondary Buttons: 0
17:17:48.934 -> Number of Axes (8-bit): 0
17:17:48.934 -> Number of Axes (10-bit): 3
17:17:48.934 -> Device Name: WMCOM

**Comment by necroware** [comment]
I probably could fix the problem. Please check the implementation from the branch:
https://github.com/necroware/gameport-adapter/tree/fix-logitech-interceptor

The reason was is, that USB HID descriptor allows only one Hat. I didn't know that and now all the secondary hats should be registered as additional axes.

**Comment by Fanbotica** [comment]
> I probably could fix the problem. Please check the implementation from the branch: https://github.com/necroware/gameport-adapter/tree/fix-logitech-interceptor
> 
> The reason was, that USB HID descriptor allows only one Hat. I didn't know that and now all the secondary hats should be registered as additional axes.

I think everything is fine now, in the "Properties of the Arduino Leonardo gaming device" panel, together with the finally working main Hat the axes "Rotation X", "Rotation Y", "Rotation Z", "Sliding indicator" now appear, I believe it is due to the transformation of the hats beyond the first into rotation axes.
Just a note, the timing of the trigger signal pulse needs to be corrected to "100u" I think it is back to "10u" in the Wingman Interceptor version.

**Comment by Fanbotica** [comment]
> > m_trigger.pulse(100u);
> 
> You didn't mention it before. Why should this be changed to 100u? I'm afraid, that other Logitech joysticks will not work with that long trigger pulse. Don't forget, that the same code is used for all Logitech joysticks, which use ADI protocol, not only the Interceptor. Doesn't it work with pulse of 10u for your device? If not, does it work with something below 100? We have to find a universal value which would fit all joysticks.

Forgive me, in my rush this morning I must have made a confusion with the copy and paste... 

I apologize, but in the code working with my Logitech Wingman Interceptor the lines I changed are this:

`delayMicroseconds(4000);`

and especially this:

`       m_trigger.pulse(100u);`

So as you say, I believe that at this point we need to find a value for the duration of the trigger pulse that works for everyone.
I apologize again.

**Comment by necroware** [comment]
Thank you. I don't think, that the cooldown of 4000 vs 5000 would make a difference, so that should probably remain unchanged. As for the pulse duration please try to go down with the value as much as possible and tell me where your device stops to work. I then try that value with the other joystick which I have at hand. May be we can meet somewhere in the middle.

**Comment by Fanbotica** [comment]
> Thank you. I don't think, that the cooldown of 4000 vs 5000 would make a difference, so that should probably remain unchanged. As for the pulse duration please try to go down with the value as much as possible and tell me where your device stops to work. I then try that value with the other joystick which I have at hand. May be we can meet somewhere in the middle.

So, I performed the tests necessary to identify the minimum trigger signal timing value to allow the detection of the Logitech Wingman Interceptor joystick peripheral, and this value turns out to be without a shadow of a doubt "20u",
So I'm quoting the entire correct line:

`       m_trigger.pulse(20u);`

Thanks again and I hope I was helpful.

**Comment by necroware** [comment]
Thank you very much! I updated and tested the value with my Logitech WingMan Extreme Digital and it seems to work fine there as well. I think Interceptor can now be officially be added to the list of working devices. Thanks for testing.
