### ISSUE TITLE
how do you play your games with the current adapter?

### ISSUE THREAD

**Issue by opensourcerebel** [necroware/gameport-adapter#79]
The current adapter works pretty good (all my M$ joysticks and FFB wheels work) I had some relative success with using it under ubuntu 18.04 to play Starwars Racer/ColinMcRae rally or Flatout 2 (ubuntu 20.04 and 22.04 was complete trash). On 18.04 it works decent but the gravity in SWR is a bit messed up and sometimes you stick to the walls. Flatout2 sometimes becomes choppy.
I decided to install win7 which worked on of my old machines ... but then I was immediately in driver hell :)

So I have decided to spare my self the exploration and ask around ... so how do you play these old games to get a better experience from your controllers (old pc + all the dirvers or some linux with wine or?)?

**Comment by necroware** [comment]
Please use discussions area for this. You can create a new discussion here:
https://github.com/necroware/gameport-adapter/discussions

**Comment by opensourcerebel** [comment]
In case someone lands here: https://github.com/necroware/gameport-adapter/discussions/80
