### ISSUE TITLE
Sparkfun Pro Micro drivers for Windows 98SE?

### ISSUE THREAD

**Issue by hugonl31** [necroware/gameport-adapter#83]
Hi, as the title says, does anyone know if the board can be used in Windows 98?

**Comment by necroware** [comment]
I'm trying to clean up some open issues and since I don't have a lot of time to keep track of everything, all unrelated questions will be closed. This question is about Sparkfun Pro Micro and not this project.

**Comment by Invictaz** [comment]
For now it seems it cannot as it presents itself as a CDC device
